# Singular Value Decomposition (SVD)
This notebook demonstrates the implementation of SVD for matrix decomposition.

In [6]:
# Import required libraries
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from numpy.linalg import eigh, norm

## Step 1: Define the input matrix A

In [21]:
# Define a 3x3 test matrix
A = np.array([[-5, 2, 3],
               [3, 5, 1],
               [-3, 1, -5]])

## Step 2: Compute the Gram matrix (A^T * A)

In [22]:
# Gram matrix: A^T @ A
gram_matrix = A.T @ A
gram_matrix

array([[43,  2,  3],
       [ 2, 30,  6],
       [ 3,  6, 35]])

## Step 3: Compute eigenvalues and eigenvectors

In [23]:
# Compute eigenvalues (ev) and eigenvectors (V) of A^T @ A
eigenvalues, V = eigh(A.T @ A)
# Note: eigh returns eigenvalues in ascending order
print(f"Eigenvalues: {eigenvalues}")

In [24]:
# Display the first eigenvector (corresponding to smallest eigenvalue)
first_eigenvector = V[:, 0]
first_eigenvector

array([ 0.        , -0.83205029,  0.5547002 ])

## Step 4: Compute left singular vectors (U)

In [30]:
# Compute left singular vectors by normalizing A @ V[:, i]
u0 = A @ V[:, 0] / norm(A @ V[:, 0])  # First left singular vector
u1 = A @ V[:, 1] / norm(A @ V[:, 1])  # Second left singular vector
u2 = A @ V[:, 2] / norm(A @ V[:, 2])  # Third left singular vector

In [31]:
# Combine left singular vectors into matrix U
U = np.array([u0, u1, u2]).T
print(f"U shape: {U.shape}")
print(f"U matrix:\n{U}")

## Step 5: Compute singular values (diagonal matrix)

In [32]:
# Compute singular value matrix D = U^T @ A @ V
# This should be a diagonal matrix with singular values on the diagonal
D = np.round(U.T @ A @ V, decimals=5)
print("Singular value matrix D:")
print(D)

Singular value matrix D:
[[ 5.09902   0.       -0.      ]
 [ 0.        6.072635  0.      ]
 [-0.        0.        6.717373]]


## Step 6: SVD Reconstruction and Verification

In [33]:
# Reconstruct matrix A from SVD components: A = U @ D @ V^T
A_reconstructed = U @ D @ V.T

# SVD Decomposition Components:
# - A is [m × n] (original matrix)
# - U is [m × r] (left singular vectors, orthonormal columns)
# - D is [r × r] (diagonal matrix with singular values)
# - V^T is [r × n] (right singular vectors, orthonormal rows)
#
# Where:
# - U contains the left singular vectors (basis for row space)
# - D contains the singular values (sorted, non-zero on diagonal, zeros elsewhere)
# - V contains the right singular vectors (basis for column space)

## Step 7: Verify the reconstruction

In [34]:
# Display original and reconstructed matrices
print("Original matrix A:")
print(A)

print("\nReconstructed matrix A (from SVD):")
print(A_reconstructed)

# Calculate reconstruction error
reconstruction_error = np.linalg.norm(A - A_reconstructed)
print(f"\nReconstruction error: {reconstruction_error:.2e}")

# The error should be very small (close to machine precision)

Original matrix A:
[[-5  2  3]
 [ 3  5  1]
 [-3  1 -5]]

Reconstructed matrix A (from SVD):
[[-4.99999992  2.0000001   3.00000015]
 [ 2.99999975  5.00000022  0.99999972]
 [-2.99999975  1.00000035 -5.0000001 ]]

Reconstruction error: 1.61e-07
