In [6]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from numpy.linalg import eigh, norm



In [21]:
A = np.array([[-5,2,3],
               [3,5,1],
               [-3,1,-5]])

In [22]:
A.T@A

array([[43,  2,  3],
       [ 2, 30,  6],
       [ 3,  6, 35]])

In [23]:
ev, V= eigh(A.T@A)

In [24]:
V[:,0]

array([ 0.        , -0.83205029,  0.5547002 ])

In [30]:
u0 = A@V[:,0]/norm(A@V[:,0])# column 1
u1 = A@V[:,1]/norm(A@V[:,1])# column 2
u2 = A@V[:,2]/norm(A@V[:,2])# column 3

In [31]:
U=np.array([u0,u1,u2]).T

In [32]:
D=np.round(U.T@A@V, decimals = 6)
print(D)

[[ 5.09902   0.       -0.      ]
 [ 0.        6.072635  0.      ]
 [-0.        0.        6.717373]]


In [33]:
AA =  U@D@V.T #is the SVD
# A is [mxn]
# U very few columns and m rows [mxr]
# D is diagnal [rxr]
# V small number of rows [nxr]


# U : left singular vector
# D : Singular value (Diagonal metrix, sorted none zero values are on main diagonal and rest are zero)
# V : Right singular vector

In [34]:
print(A)
print(AA)

[[-5  2  3]
 [ 3  5  1]
 [-3  1 -5]]
[[-4.99999992  2.0000001   3.00000015]
 [ 2.99999975  5.00000022  0.99999972]
 [-2.99999975  1.00000035 -5.0000001 ]]
